// Context Action Types
export const CONTEXT_ACTIONS = {
  SET_SETTINGS_MESSAGES: 'SET_SETTINGS_MESSAGES',
  ADD_SETTINGS_MESSAGE: 'ADD_SETTINGS_MESSAGE',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SET_CAMERA_LOADING: 'SET_CAMERA_LOADING',
  SET_CAMERA_FADING: 'SET_CAMERA_FADING',
}; 